/* ###################################################################
**     Filename    : ADC0Events.c
**     Project     : EA076_PE
**     Processor   : MKL25Z128VLK4
**     Component   : Events
**     Version     : Driver 01.00
**     Compiler    : GNU C Compiler
**     Date/Time   : 2019-04-13, 10:42, # CodeGen: 61
**     Abstract    :
**         This is user's event module.
**         Put your event handler code here.
**     Contents    :
**         AD1_OnEnd            - void AD1_OnEnd(void);
**         AD1_OnCalibrationEnd - void AD1_OnCalibrationEnd(void);
**
** ###################################################################*/
/*!
** @file ADC0Events.c
** @version 01.00
** @brief
**         This is user's event module.
**         Put your event handler code here.
**
** @author Guilherme R C <guilherme.riciolic@gmail.com>
*/         
/*!
**  @addtogroup ADC0Events_module ADC0Events module documentation
**  @{
*/         
/* MODULE ADC0Events */

#include <ADC0.h>
#include <event_ring_buff.h>
#include <stdint.h>
#include "ADC0Events.h"

#ifdef __cplusplus
extern "C" {
#endif 


/* User includes (#include below this line is not maintained by Processor Expert) */
#include <temp.h>

/*! \brief A handler that reads the last ADC measurement
**
**	This handler accumulates the subsequent readings from the ADC until
**	the maximum number of samples is achieved. Thereafter, an average is
**	calculated and an event is inserted in the event ring buffer,
**	indicating that a new temperature measurement is ready to be
**	published.
**
** 	Follows the description generated by ProcessorExpert.
** ===================================================================
**     Event       :  AD1_OnEnd (module ADC0Events)
**
**     Component   :  ADC0 [ADC]
**     Description :
**         This event is called after the measurement (which consists
**         of <1 or more conversions>) is/are finished.
**         The event is available only when the <Interrupt
**         service/event> property is enabled.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
void AD1_OnEnd(void)
{
	static uint16_t curr_reading = 0;
	static uint32_t curr_avg_reading = 0;	// the max sum needs 25 bits

	temp_info.curr_samples_number++;

	ADC0_GetValue16(&curr_reading);

	curr_avg_reading += curr_reading;

	if(temp_info.curr_samples_number == MAX_NUMBER_OF_SAMPLES)
	{
		curr_avg_reading /= temp_info.curr_samples_number;
		temp_info.raw_temperature = curr_avg_reading;

		event_ring_buff_insert_event(NEW_TEMPERATURE_MEAS);

		temp_info.curr_samples_number = 0;
		curr_avg_reading = 0;
	}
}

/*
** ===================================================================
**     Event       :  AD1_OnCalibrationEnd (module ADC0Events)
**
**     Component   :  ADC0 [ADC]
**     Description :
**         This event is called when the calibration has been finished.
**         User should check if the calibration pass or fail by
**         Calibration status method./nThis event is enabled only if
**         the <Interrupt service/event> property is enabled.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
void AD1_OnCalibrationEnd(void)
{
  /* Write your code here ... */
}

/* END ADC0Events */

#ifdef __cplusplus
}  /* extern "C" */
#endif 

/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.5 [05.21]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
