 /* ###################################################################
**     Filename    : Events.c
**     Project     : EA076_D
**     Processor   : MKL25Z128VLK4
**     Component   : Events
**     Version     : Driver 01.00
**     Compiler    : GNU C Compiler
**     Date/Time   : 2019-03-18, 16:31, # CodeGen: 0
**     Abstract    :
**         This is user's event module.
**         Put your event handler code here.
**     Contents    :
**         CPU_OnNMIINT - void CPU_OnNMIINT(void);
**
** ###################################################################*/
/*!
** @file Events.c
** @version 01.00
** @brief
**         This is user's event module.
**         Put your event handler code here.
**
** @author Guilherme R C <guilherme.riciolic@gmail.com
*/         
/*!
**  @addtogroup Events_module Events module documentation
**  @{
*/         
/* MODULE Events */

#include <display.h>
#include <kboard.h>
#include <KBOARD_C1.h>
#include <KBOARD_C2.h>
#include <KBOARD_C3.h>
#include <LEDB.h>
#include <LEDG.h>
#include <LEDR.h>
#include <PE_Types.h>
#include <PORT_PDD.h>
#include <stdint.h>
#include <WAIT1.h>
#include "Events.h"

#ifdef __cplusplus
extern "C" {
#endif 


/* User includes (#include below this line is not maintained by Processor Expert) */

/*
** ===================================================================
**     Event       :  CPU_OnNMIINT (module Events)
**
**     Component   :  CPU [MKL25Z128LK4]
*/
/*!
**     @brief
**         This event is called when the Non maskable interrupt had
**         occurred. This event is automatically enabled when the [NMI
**         interrupt] property is set to 'Enabled'.
*/
/* ===================================================================*/
void CPU_OnNMIINT(void)
{
  /* Write your code here ... */
}

/*! @brief An event handler called when a button from column 3 is
** either pressed or released
** ===================================================================
**     Event       :  KBOARD_C3_OnInterrupt (module Events)
**
**     Component   :  KBOARD_C3 [ExtInt]
**     Description :
**         This event is called when an active signal edge/level has
**         occurred.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
void KBOARD_C3_OnInterrupt(void)
{
	static KBOARD_BUTTON_STATE state = RELEASED;

	/*! Debouncing solution */
	WAIT1_Waitms(DEBOUNCING_DELAY);

	if(KBOARD_C3_GetVal() == FALSE)
	{
		LEDR_PutVal(TRUE);
		LEDG_PutVal(TRUE);
		LEDB_PutVal(FALSE);

		state = PRESSED;
	}
	else
	{
		LEDB_PutVal(TRUE);

		state = RELEASED;
	}

	uint8_t row = 0;
	if(state == PRESSED)
	{
		for(row = 1; row < KBOARD_NUMBER_OF_ROWS + 1; row++)
		{
			kboard_deactivate_row(row);
			if(KBOARD_C3_GetVal() == TRUE)	break;
		}
	}

	PORT_PDD_ClearPinInterruptFlag(PORTA_BASE_PTR, KBOARD_C3_PIN);

	kboard_activate_rows();
}


/*! @brief An event handler called when a button from column 2 is
 * either pressed or released
 *
** ===================================================================
**     Event       :  KBOARD_C2_OnInterrupt (module Events)
**
**     Component   :  KBOARD_C2 [ExtInt]
**     Description :
**         This event is called when an active signal edge/level has
**         occurred.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
void KBOARD_C2_OnInterrupt(void)
{
	static KBOARD_BUTTON_STATE state = RELEASED;

	/*! Debouncing solution */
	WAIT1_Waitms(DEBOUNCING_DELAY);

	/*! If this interruption was generated by a falling edge (button
	 * pressed) */
	if(KBOARD_C2_GetVal() == FALSE)
	{
		LEDR_PutVal(TRUE);
		LEDG_PutVal(FALSE);
		LEDB_PutVal(TRUE);

		state = PRESSED;
	}
	/*! Or it was generated by a rising edge (button released) */
	else
	{
		LEDG_PutVal(TRUE);

		state = RELEASED;
	}

	uint8_t row = 0;
	if(state == PRESSED)
	{
		for(row = 1; row < KBOARD_NUMBER_OF_ROWS + 1; row++)
		{
			kboard_deactivate_row(row);
			if(KBOARD_C2_GetVal() == TRUE)	break;
		}
	}

	PORT_PDD_ClearPinInterruptFlag(PORTA_BASE_PTR, KBOARD_C2_PIN);

	kboard_activate_rows();
}

/*!@brief An event handler called when a button from column 1 is
** either pressed or released
** ===================================================================
**     Event       :  KBOARD_C1_OnInterrupt (module Events)
**
**     Component   :  KBOARD_C1 [ExtInt]
**     Description :
**         This event is called when an active signal edge/level has
**         occurred.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
void KBOARD_C1_OnInterrupt(void)
{
	static KBOARD_BUTTON_STATE state = RELEASED;

	/*! Debouncing solution */
	WAIT1_Waitms(DEBOUNCING_DELAY);

	/*! If this interruption was generated by a falling edge (button
	 * pressed) */
	if(KBOARD_C1_GetVal() == FALSE)
	{
		LEDR_PutVal(FALSE);
		LEDG_PutVal(TRUE);
		LEDB_PutVal(TRUE);

		state = PRESSED;
	}
	/*! Or it was generated by a rising edge (button released) */
	else
	{
		LEDR_PutVal(TRUE);

		state = RELEASED;
	}

	uint8_t row = 0;
	if(state == PRESSED)
	{
		for(row = 1; row < KBOARD_NUMBER_OF_ROWS + 1; row++)
		{
			kboard_deactivate_row(row);
			if(KBOARD_C1_GetVal() == TRUE)	break;
		}
	}

	PORT_PDD_ClearPinInterruptFlag(PORTA_BASE_PTR, KBOARD_C1_PIN);

	kboard_activate_rows();
}

/*
** ===================================================================
**     Event       :  Cpu_OnNMIINT (module Events)
**
**     Component   :  CPU [MKL25Z128LK4]
*/
/*!
**     @brief
**         This event is called when the Non maskable interrupt had
**         occurred. This event is automatically enabled when the [NMI
**         interrupt] property is set to 'Enabled'.
*/
/* ===================================================================*/
void Cpu_OnNMIINT(void)
{
  /* Write your code here ... */
}

/* END Events */

#ifdef __cplusplus
}  /* extern "C" */
#endif 

/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.5 [05.21]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
