 /* ###################################################################
**     Filename    : Events.c
**     Project     : EA076_D
**     Processor   : MKL25Z128VLK4
**     Component   : Events
**     Version     : Driver 01.00
**     Compiler    : GNU C Compiler
**     Date/Time   : 2019-03-18, 16:31, # CodeGen: 0
**     Abstract    :
**         This is user's event module.
**         Put your event handler code here.
**     Contents    :
**         CPU_OnNMIINT - void CPU_OnNMIINT(void);
**
** ###################################################################*/
/*!
** @file Events.c
** @version 01.00
** @brief
**         This is user's event module.
**         Put your event handler code here.
**
** @author Guilherme R C <guilherme.riciolic@gmail.com
*/         
/*!
**  @addtogroup Events_module Events module documentation
**  @{
*/         
/* MODULE Events */

#include <ADC0.h>
#include <comm.h>
#include <console.h>
#include <display.h>
#include <event_buff.h>
#include <kboard.h>
#include <KBOARD_C1.h>
#include <KBOARD_C2.h>
#include <KBOARD_C3.h>
#include <PE_Types.h>
#include <PORT_PDD.h>
#include <stddef.h>
#include <stdint.h>
#include <temp.h>
#include <UART0.h>
#include <UART2.h>
#include <WAIT1.h>
#include "Events.h"

#ifdef __cplusplus
extern "C" {
#endif 


/* User includes (#include below this line is not maintained by Processor Expert) */
extern volatile bool external_interrupt;
extern volatile KBOARD_KEY_TYPE last_key_pressed;
extern DISPLAY_TIMEOUT display_timeout;
volatile bool timeout_reached = FALSE;

/*
** ===================================================================
**     Event       :  CPU_OnNMIINT (module Events)
**
**     Component   :  CPU [MKL25Z128LK4]
*/
/*!
**     @brief
**         This event is called when the Non maskable interrupt had
**         occurred. This event is automatically enabled when the [NMI
**         interrupt] property is set to 'Enabled'.
*/
/* ===================================================================*/
void CPU_OnNMIINT(void)
{
  /* Write your code here ... */
}

/*! @brief An event handler called when a button from column 3 is
** either pressed or released
** ===================================================================
**     Event       :  KBOARD_C3_OnInterrupt (module Events)
**
**     Component   :  KBOARD_C3 [ExtInt]
**     Description :
**         This event is called when an active signal edge/level has
**         occurred.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
void KBOARD_C3_OnInterrupt(void)
{
	static KBOARD_BUTTON_STATE state = RELEASED;
	static KBOARD_KEY_TYPE key_pressed;

	/*! Debouncing solution */
	WAIT1_Waitms(DEBOUNCING_DELAY);

	/*! If this interruption was generated by a falling edge (button
	 * pressed) */
	if(KBOARD_C3_GetVal() == FALSE)
		state = PRESSED;
	/*! Or it was generated by a rising edge (button released) */
	else
		state = RELEASED;

	uint8_t row = 0;
	if(state == PRESSED)
	{
		for(row = 1; row < KBOARD_NUMBER_OF_ROWS + 1; row++)
		{
			kboard_deactivate_row(row);
			if(KBOARD_C3_GetVal() == TRUE)	break;
		}

		if(row == 1)
			key_pressed = KEY_3;
		else if(row == 2)
			key_pressed = KEY_6;
		else if(row == 3)
			key_pressed = KEY_9;
		else if(row == 4)
			key_pressed = KEY_HASHTAG;
	}

	//display_write_line(1, "Column 3");

	PORT_PDD_ClearPinInterruptFlag(PORTA_BASE_PTR, KBOARD_C3_PIN);

	kboard_activate_rows();

	external_interrupt = TRUE;
	last_key_pressed = key_pressed;
}


/*! @brief An event handler called when a button from column 2 is
 * either pressed or released
 *
** ===================================================================
**     Event       :  KBOARD_C2_OnInterrupt (module Events)
**
**     Component   :  KBOARD_C2 [ExtInt]
**     Description :
**         This event is called when an active signal edge/level has
**         occurred.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
void KBOARD_C2_OnInterrupt(void)
{
	static KBOARD_BUTTON_STATE state = RELEASED;
	static KBOARD_KEY_TYPE key_pressed;

	/*! Debouncing solution */
	WAIT1_Waitms(DEBOUNCING_DELAY);

	/*! If this interruption was generated by a falling edge (button
	 * pressed) */
	if(KBOARD_C2_GetVal() == FALSE)
		state = PRESSED;
	/*! Or it was generated by a rising edge (button released) */
	else
		state = RELEASED;

	uint8_t row = 0;
	if(state == PRESSED)
	{
		for(row = 1; row < KBOARD_NUMBER_OF_ROWS + 1; row++)
		{
			kboard_deactivate_row(row);
			if(KBOARD_C2_GetVal() == TRUE)	break;
		}

		if(row == 1)
			key_pressed = KEY_2;
		else if(row == 2)
			key_pressed = KEY_5;
		else if(row == 3)
			key_pressed = KEY_8;
		else if(row == 4)
			key_pressed = KEY_0;
	}

	//display_write_line(1, "Column 2");

	PORT_PDD_ClearPinInterruptFlag(PORTA_BASE_PTR, KBOARD_C2_PIN);

	kboard_activate_rows();

	external_interrupt = TRUE;
	last_key_pressed = key_pressed;

}

/*!@brief An event handler called when a button from column 1 is
** either pressed or released
** ===================================================================
**     Event       :  KBOARD_C1_OnInterrupt (module Events)
**
**     Component   :  KBOARD_C1 [ExtInt]
**     Description :
**         This event is called when an active signal edge/level has
**         occurred.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
void KBOARD_C1_OnInterrupt(void)
{
	static KBOARD_BUTTON_STATE state = RELEASED;
	static KBOARD_KEY_TYPE key_pressed;

	/*! Debouncing solution */
	WAIT1_Waitms(DEBOUNCING_DELAY);

	/*! If this interruption was generated by a falling edge (button
	 * pressed) */
	if(KBOARD_C1_GetVal() == FALSE)
		state = PRESSED;
	/*! Or it was generated by a rising edge (button released) */
	else
		state = RELEASED;

	uint8_t row = 0;
	if(state == PRESSED)
	{
		for(row = 1; row < KBOARD_NUMBER_OF_ROWS + 1; row++)
		{
			kboard_deactivate_row(row);
			if(KBOARD_C1_GetVal() == TRUE)	break;
		}

		if(row == 1)
			key_pressed = KEY_1;
		else if(row == 2)
			key_pressed = KEY_4;
		else if(row == 3)
			key_pressed = KEY_7;
		else if(row == 4)
			key_pressed = KEY_ASTERISK;
	}

	//display_write_line(1, "Column 1");

	PORT_PDD_ClearPinInterruptFlag(PORTA_BASE_PTR, KBOARD_C1_PIN);

	kboard_activate_rows();

	external_interrupt = TRUE;
	last_key_pressed = key_pressed;
}

/*
** ===================================================================
**     Event       :  Cpu_OnNMIINT (module Events)
**
**     Component   :  CPU [MKL25Z128LK4]
*/
/*!
**     @brief
**         This event is called when the Non maskable interrupt had
**         occurred. This event is automatically enabled when the [NMI
**         interrupt] property is set to 'Enabled'.
*/
/* ===================================================================*/
void Cpu_OnNMIINT(void)
{
  /* Write your code here ... */
}

/*
** ===================================================================
**     Event       :  RTC1_OnSecond (module Events)
**
**     Component   :  RTC [RTC_LDD]
*/
/*!
**     @brief
**         Called each second if OnSecond event is enabled (see
**         [SetEventMask] and [GetEventMask] methods) and RTC device is
**         enabled. This event is available only if [Interrupt
**         service/event] is enabled.
**     @param
**         UserDataPtr     - Pointer to the user or
**                           RTOS specific data. This pointer is passed
**                           as the parameter of Init method. 
*/
/* ===================================================================*/
void RTC1_OnSecond(LDD_TUserData *UserDataPtr)
{
	/*! Checks whether the timeout was triggered or not */
	if(display_timeout.triggered = TRUE)
		display_timeout.timer++;

	/*! If timer has reached the target timeout configured, return to
	 * main menu */
	if(display_timeout.timer == display_timeout.target)
	{
		timeout_reached = TRUE;
		display_unset_timeout();
	}
}

/*! \brief A handler that reads the last ADC measurement
**
**	This handler accumulates the subsequent readings from the ADC until
**	the maximum number of samples is achieved. Thereafter, an average is
**	calculated and an event is inserted in the event ring buffer,
**	indicating that a new temperature measurement is ready to be
**	published.
**
** 	Follows the description generated by ProcessorExpert.
** ===================================================================
**     Event       :  AD1_OnEnd (module ADC0Events)
**
**     Component   :  ADC0 [ADC]
**     Description :
**         This event is called after the measurement (which consists
**         of <1 or more conversions>) is/are finished.
**         The event is available only when the <Interrupt
**         service/event> property is enabled.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
void AD1_OnEnd(void)
{
	static uint16_t curr_reading = 0;
	static uint32_t curr_avg_reading = 0;	// the max sum needs 25 bits

	temp_info.curr_samples_number++;

	ADC0_GetValue16(&curr_reading);

	curr_avg_reading += curr_reading;

	if(temp_info.curr_samples_number == MAX_NUMBER_OF_SAMPLES)
	{
		curr_avg_reading /= temp_info.curr_samples_number;
		temp_info.raw_temperature = curr_avg_reading;

		event_buff_insert_event(NEW_TEMPERATURE_MEAS);

		temp_info.curr_samples_number = 0;
		curr_avg_reading = 0;
	}
}

/*
** ===================================================================
**     Event       :  AD1_OnCalibrationEnd (module Events)
**
**     Component   :  ADC0 [ADC]
**     Description :
**         This event is called when the calibration has been finished.
**         User should check if the calibration pass or fail by
**         Calibration status method./nThis event is enabled only if
**         the <Interrupt service/event> property is enabled.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
void AD1_OnCalibrationEnd(void)
{
  /* Write your code here ... */
}

/*
** ===================================================================
**     Event       :  UART0_OnError (module Events)
**
**     Component   :  UART0 [AsynchroSerial]
**     Description :
**         This event is called when a channel error (not the error
**         returned by a given method) occurs. The errors can be read
**         using <GetError> method.
**         The event is available only when the <Interrupt
**         service/event> property is enabled.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
void UART0_OnError(void)
{
  /* Write your code here ... */
}

/*! @brief A handler that echoes the received char and also insert an
 * event in the event ring buffer if a complete message was received
**
** 	Follows the description generated by ProcessorExpert.
** ===================================================================
**     Event       :  UART0_OnRxChar (module UART0Events)
**
**     Component   :  UART0 [AsynchroSerial]
**     Description :
**         This event is called after a correct character is received.
**         The event is available only when the <Interrupt
**         service/event> property is enabled and either the <Receiver>
**         property is enabled or the <SCI output mode> property (if
**         supported) is set to Single-wire mode.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
void UART0_OnRxChar(void)
{
	/*!
	 * Echoes the just received char
	 * Using the LOG function ensures that the next handling of an
	 * event will wait this echoing to be done. This is important as
	 * during this handling a LOG function can also be used and this
	 * message would be overwritten.
	 */
	console_write(NULL, UART0_GetPtrToLastRecvChar());

	if(UART0_HasACompleteMessage())
		event_buff_insert_event(NEW_MESSAGE_FROM_TERMINAL);
}

/*! @brief A function that indicates that a character was sent into the
 * TX channel of UART0. This handler is used to trigger chained calls
 * to send a message.
**
** 	Follows the description generated by ProcessorExpert.
** ===================================================================
**     Event       :  UART0_OnTxChar (module UART0Events)
**
**     Component   :  UART0 [AsynchroSerial]
**     Description :
**         This event is called after a character is transmitted.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
void UART0_OnTxChar(void)
{
	static uint8_t curr_idx = 0;

	UART0_TComData curr_char = console_info.buffer[curr_idx++];
	if(curr_char != '\0')
	{
		UART0_SendChar(curr_char);
	}
	else
	{
		curr_idx = 0;

		console_info.status = DONE;
	}
}

/*
** ===================================================================
**     Event       :  UART2_OnError (module Events)
**
**     Component   :  UART2 [AsynchroSerial]
**     Description :
**         This event is called when a channel error (not the error
**         returned by a given method) occurs. The errors can be read
**         using <GetError> method.
**         The event is available only when the <Interrupt
**         service/event> property is enabled.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
void UART2_OnError(void)
{
  /* Write your code here ... */
}

/*! @brief A handler that checks if a complete message has been
 * received. If so, it inserts a new event in the event ring buffer.
**
** 	Follows the description generated by ProcessorExpert.
** ===================================================================
**     Event       :  UART0_OnRxChar (module UART0Events)
**
**     Component   :  UART0 [AsynchroSerial]
**     Description :
**         This event is called after a correct character is received.
**         The event is available only when the <Interrupt
**         service/event> property is enabled and either the <Receiver>
**         property is enabled or the <SCI output mode> property (if
**         supported) is set to Single-wire mode.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
void UART2_OnRxChar(void)
{
	if(UART2_HasACompleteMessage())
		event_buff_insert_event(NEW_MESSAGE_FROM_BROKER);
}

/*! @brief A handler that indicates that a character was sent into the
 * TX channel of UART2. This handler is used to trigger chained calls
 * until a complete message is sent.
**
** 	Follows the description generated by ProcessorExpert.
** ===================================================================
**     Event       :  UART2_OnTxChar (module UART2Events)
**
**     Component   :  UART2 [AsynchroSerial]
**     Description :
**         This event is called after a character is transmitted.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
void UART2_OnTxChar(void)
{
	static uint8_t curr_idx = 0;

	UART2_TComData curr_char = comm_info.message_out[curr_idx++];
	if(curr_char != '\0')
	{
		UART2_SendChar(curr_char);
	}
	else
	{
		curr_idx = 0;
		comm_info.sending_status = DONE;
	}
}

/*! \brief A handler that requests a new ADC measurement at each 2 ms
**
** 	Follows the description generated by ProcessorExpert.
** ===================================================================
**     Event       :  TI1_OnInterrupt (module TimerInt0Events)
**
**     Component   :  TimerInt0 [TimerInt]
**     Description :
**         When a timer interrupt occurs this event is called (only
**         when the component is enabled - <Enable> and the events are
**         enabled - <EnableEvent>). This event is enabled only if a
**         <interrupt service/event> is enabled.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
void TI1_OnInterrupt(void)
{
	ADC0_Measure(FALSE);
}

/* END Events */

#ifdef __cplusplus
}  /* extern "C" */
#endif 

/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.5 [05.21]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
