/* ###################################################################
 **     Filename    : TimerInt1Events.c
 **     Project     : EA076_PE
 **     Processor   : MKL25Z128VLK4
 **     Component   : Events
 **     Version     : Driver 01.00
 **     Compiler    : GNU C Compiler
 **     Date/Time   : 2019-05-05, 02:00, # CodeGen: 142
 **     Abstract    :
 **         This is user's event module.
 **         Put your event handler code here.
 **     Contents    :
 **         TI1_OnInterrupt0 - void TI1_OnInterrupt0(void);
 **
 ** ###################################################################*/
/*!
 ** @file TimerInt1Events.c
 ** @version 01.00
 ** @brief
 **         This is user's event module.
 **         Put your event handler code here.
 */
/*!
 **  @addtogroup TimerInt1Events_module TimerInt1Events module documentation
 **  @{
 */
/* MODULE TimerInt1Events */

#include <display.h>
#include <PE_Types.h>
#include <stamp.h>
#include <stdint.h>
#include <temp.h>
#include <UTIL1.h>
#include "TimerInt1Events.h"

#ifdef __cplusplus
extern "C" {
#endif 


/* User includes (#include below this line is not maintained by Processor Expert) */
typedef enum
{
	CLEANING,
	GETTING_CURR_TIME,
	ASSEMBLING_STRING,
	WRITING_STRING
} DISPLAY_STATE_ENUM;

#define DISPLAY_STATE_ENUM_RANGE	2

#define ITERATION_MAX	4

static LDD_RTC_TTime current_time;

/*! @brief A timer interrupt handler used to update the display
 *
 * This handler implements a FSM, in which the sequence of states is:
 *
 * 	CLEANING			-	Cleans line 1
 * 	CLEANING			-	Cleans line 2
 * 	CLEANING			-	Cleans line 3
 * 	GETTING_CURR_TIME	-	Gets the current time from RTC module
 * 	ASSEMBLING_STRING	-	Assembles string to be written in line 1
 * 	WRITING_STRING		-	Writes the string in line 1
 *  ASSEMBLING_STRING	-	Assembles string to be written in line 2
 *  WRITING_STRING		-	Writes the string in line 2
 *  ASSEMBLING_STRING	-	Assembles string to be written in line 3
 * 	WRITING_STRING		-	Writes the string in line 3
 * 	and starts again.
 *
 * 	Each state is performed at each interruption.
 *
 * Follows the description generated by PE.
 *
 ** ===================================================================
 **     Event       :  TI1_OnInterrupt0 (module TimerInt1Events)
 **
 **     Component   :  TimerInt1 [TimerInt]
 **     Description :
 **         When a timer interrupt occurs this event is called (only
 **         when the component is enabled - <Enable> and the events are
 **         enabled - <EnableEvent>). This event is enabled only if a
 **         <interrupt service/event> is enabled.
 **     Parameters  : None
 **     Returns     : Nothing
 ** ===================================================================
 */
void TI1_OnInterrupt0(void)
{
	static char line_string[DISPLAY_LINE_STRING_SIZE];
	static DISPLAY_STATE_ENUM state = CLEANING;
	static uint8_t iteration = 1;

	/*! TODO: Check if the current implementation makes sense, I'm sleepy */

	switch(state)
	{

	/*! Cleans each line (being used: 1-3) of the display */
	case CLEANING:
	{
		display_clean_line(iteration++);

		if(iteration == ITERATION_MAX)
		{
			iteration = 1;
			state = GETTING_CURR_TIME;
		}

		break;
	}
	/*! Gets the current time from RTC module */
	case GETTING_CURR_TIME:
	{
		stamp_get_time(&current_time);
		//RTC_GetTime(RTC_dd_ptr, &current_time);
		state = ASSEMBLING_STRING;

		break;
	}
	/*! Assembles the string to be written in the line indexed by
	 * 'iteration' */
	case ASSEMBLING_STRING:
	{
		if(iteration == 1)
		{
			/*! Assembles the string "    MM/DD/YYYY" */
			UTIL1_strcpy(line_string, DISPLAY_LINE_STRING_SIZE,
					"    ");
			UTIL1_strcatNum32uFormatted(line_string,
								DISPLAY_LINE_STRING_SIZE, current_time.Month, '0', 2);
			UTIL1_strcat(line_string, DISPLAY_LINE_STRING_SIZE, "/");
			UTIL1_strcatNum32uFormatted(line_string,
					DISPLAY_LINE_STRING_SIZE, current_time.Day, '0', 2);
			UTIL1_strcat(line_string, DISPLAY_LINE_STRING_SIZE, "/");
			UTIL1_strcatNum32uFormatted(line_string,
					DISPLAY_LINE_STRING_SIZE, current_time.Year, '0', 4);
		}
		else if(iteration == 2)
		{

			/*! Assembles the string "Time: HH:MM:SS" */
			UTIL1_strcpy(line_string, DISPLAY_LINE_STRING_SIZE,
					"Time: ");
			UTIL1_strcatNum32uFormatted(line_string,
					DISPLAY_LINE_STRING_SIZE, current_time.Hour, '0', 2);
			UTIL1_strcat(line_string, DISPLAY_LINE_STRING_SIZE, ":");
			UTIL1_strcatNum32uFormatted(line_string,
					DISPLAY_LINE_STRING_SIZE, current_time.Minute, '0', 2);
			UTIL1_strcat(line_string, DISPLAY_LINE_STRING_SIZE, ":");
			UTIL1_strcatNum32uFormatted(line_string,
					DISPLAY_LINE_STRING_SIZE, current_time.Second, '0', 2);
		}
		else if(iteration == 3)
		{
			/*! Assembles the string "Temp:   TT.T C" */
			UTIL1_strcpy(line_string, DISPLAY_LINE_STRING_SIZE,
					"Temp:   ");
			UTIL1_strcat(line_string, DISPLAY_LINE_STRING_SIZE, temp_info.message);
			UTIL1_strcat(line_string, DISPLAY_LINE_STRING_SIZE, " C");
		}

		state = WRITING_STRING;

		break;
	}
	/*! Writes the string in the line indexed by 'iteration' */
	case WRITING_STRING:
	{
		display_write_line(iteration, line_string);

		if(++iteration < ITERATION_MAX)
			state = ASSEMBLING_STRING;
		else
		{
			iteration = 1;
			state = CLEANING;
		}

		break;
	}
	}
}

/* END TimerInt1Events */

#ifdef __cplusplus
}  /* extern "C" */
#endif 

/*!
 ** @}
 */
/*
 ** ###################################################################
 **
 **     This file was created by Processor Expert 10.5 [05.21]
 **     for the Freescale Kinetis series of microcontrollers.
 **
 ** ###################################################################
 */
