/* ###################################################################
**     Filename    : UART0Events.c
**     Project     : EA076_PE
**     Processor   : MKL25Z128VLK4
**     Component   : Events
**     Version     : Driver 01.00
**     Compiler    : GNU C Compiler
**     Date/Time   : 2019-03-29, 22:11, # CodeGen: 42
**     Abstract    :
**         This is user's event module.
**         Put your event handler code here.
**     Contents    :
**         UART0_OnError  - void UART0_OnError(void);
**         UART0_OnRxChar - void UART0_OnRxChar(void);
**
** ###################################################################*/
/*!
** @file UART0Events.c
** @version 01.00
** @brief
**         This is user's event module.
**         Put your event handler code here.
*/         
/*!
**  @addtogroup UART0Events_module UART0Events module documentation
**  @{
*/         
/* MODULE UART0Events */

#include "Cpu.h"
#include "Events.h"
#include "UART0Events.h"
#include "UART2Events.h"

#ifdef __cplusplus
extern "C" {
#endif 


/* User includes (#include below this line is not maintained by Processor Expert) */

/*
** ===================================================================
**     Event       :  UART0_OnError (module UART0Events)
**
**     Component   :  UART0 [AsynchroSerial]
**     Description :
**         This event is called when a channel error (not the error
**         returned by a given method) occurs. The errors can be read
**         using <GetError> method.
**         The event is available only when the <Interrupt
**         service/event> property is enabled.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
void UART0_OnError(void)
{
  /* Write your code here ... */
}

/*! \brief A handler to the data received from the Terminal.
**
** 	This function is responsible to retransmit the data received from
** 	Terminal to the ESP-01 module. It also echoes the received data.
**
** 	Follows the description generated by ProcessorExpert.
** ===================================================================
**     Event       :  UART0_OnRxChar (module UART0Events)
**
**     Component   :  UART0 [AsynchroSerial]
**     Description :
**         This event is called after a correct character is received.
**         The event is available only when the <Interrupt
**         service/event> property is enabled and either the <Receiver>
**         property is enabled or the <SCI output mode> property (if
**         supported) is set to Single-wire mode.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

void UART0_OnRxChar(void)
{
	volatile UART0_TComData received = '\0';

	UART0_RecvChar(&received);	// Receiving the char from the RX buffer

	UART0_SendChar(received);	// Echoing the received char to the Terminal
	// Retransmitting the received char to the ESP-01 module
	UART2_SendChar((UART2_TComData)received);
}

/* END UART0Events */

#ifdef __cplusplus
}  /* extern "C" */
#endif 

/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.5 [05.21]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
