/* ###################################################################
**     Filename    : UART2Events.c
**     Project     : EA076_PE
**     Processor   : MKL25Z128VLK4
**     Component   : Events
**     Version     : Driver 01.00
**     Compiler    : GNU C Compiler
**     Date/Time   : 2019-03-29, 22:15, # CodeGen: 43
**     Abstract    :
**         This is user's event module.
**         Put your event handler code here.
**     Contents    :
**         UART2_OnError  - void UART2_OnError(void);
**         UART2_OnRxChar - void UART2_OnRxChar(void);
**
** ###################################################################*/
/*!
** @file UART2Events.c
** @version 01.00
** @brief
**         This is user's event module.
**         Put your event handler code here.
*/         
/*!
**  @addtogroup UART2Events_module UART2Events module documentation
**  @{
*/         
/* MODULE UART2Events */

#include <ESP01_comm.h>
#include <PE_Types.h>
#include <stdint.h>
#include <UART2.h>
#include "Cpu.h"
#include "Events.h"
#include "UART0Events.h"
#include "UART2Events.h"

#ifdef __cplusplus
extern "C" {
#endif 


/* User includes (#include below this line is not maintained by Processor Expert) */

/*
** ===================================================================
**     Event       :  UART2_OnError (module UART2Events)
**
**     Component   :  UART2 [AsynchroSerial]
**     Description :
**         This event is called when a channel error (not the error
**         returned by a given method) occurs. The errors can be read
**         using <GetError> method.
**         The event is available only when the <Interrupt
**         service/event> property is enabled.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
void UART2_OnError(void)
{
  /* Write your code here ... */
}

/*! \brief A handler that bufferizes that received character
**
**         This module contains user's application code.
** 	This handler is responsible to bufferize the just
** 	received character.
** 	This handler also notifies the main loop when a
** 	valid message was completely received (using the
** 	message_recv flag).
**
** 	Follows the description generated by ProcessorExpert.
** ===================================================================
**     Event       :  UART0_OnRxChar (module UART0Events)
**
**     Component   :  UART0 [AsynchroSerial]
**     Description :
**         This event is called after a correct character is received.
**         The event is available only when the <Interrupt
**         service/event> property is enabled and either the <Receiver>
**         property is enabled or the <SCI output mode> property (if
**         supported) is set to Single-wire mode.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
void UART2_OnRxChar(void)
{
	static volatile uint8_t curr_idx = 0;

	UART2_RecvChar(&(message_in[curr_idx]));	// Receiving the char from RX buffer

	// Test if the buffer has a complete message
	if(message_in[curr_idx] == '\n' && message_in[curr_idx - 1] == '\r')
	{
		message_in[curr_idx + 1] = '\0';
		curr_idx = 0;

		message_recv = TRUE;
	}
	else
		curr_idx++;
}

/*! \brief A event that indicates that a new character can be sent
 *
** 	This handler is responsible for sending a character
** 	from a buffer into the TX channel of UART. It also
** 	calls the sending-char function, which, by its turn,
** 	will generate this event again, which will call the
** 	sending-char function again, and so on so forth.
** 	Therefore, a sequence of chained sending-char calls,
** 	integrated with this event, assures that the message
** 	is properly sent to the destination.
**	This handler also notifies the main loop when the
**	message was completely sent (using the message_sent
**	flag).
**
** 	Follows the description generated by ProcessorExpert.
** ===================================================================
**     Event       :  UART2_OnTxChar (module UART2Events)
**
**     Component   :  UART2 [AsynchroSerial]
**     Description :
**         This event is called after a character is transmitted.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
void UART2_OnTxChar(void)
{
	static uint8_t curr_idx = 0;

	UART2_TComData curr_char = message_out[curr_idx++];
	if(curr_char != '\0')
	{
		UART2_SendChar(curr_char);
	}
	else
	{
		curr_idx = 0;

		message_sent = TRUE;
	}
}

/* END UART2Events */

#ifdef __cplusplus
}  /* extern "C" */
#endif 

/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.5 [05.21]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
