var modules =
[
    [ "ADC0 module documentation", "group___a_d_c0__module.html", "group___a_d_c0__module" ],
    [ "AdcLdd1 module documentation", "group___adc_ldd1__module.html", "group___adc_ldd1__module" ],
    [ "ASerialLdd1 module documentation", "group___a_serial_ldd1__module.html", "group___a_serial_ldd1__module" ],
    [ "ASerialLdd2 module documentation", "group___a_serial_ldd2__module.html", "group___a_serial_ldd2__module" ],
    [ "CPU module documentation", "group___c_p_u__module.html", "group___c_p_u__module" ],
    [ "MCUC1 module documentation", "group___m_c_u_c1__module.html", null ],
    [ "PE_Const module documentation", "group___p_e___const__module.html", "group___p_e___const__module" ],
    [ "PE_Error module documentation", "group___p_e___error__module.html", "group___p_e___error__module" ],
    [ "PE_LDD module documentation", "group___p_e___l_d_d__module.html", "group___p_e___l_d_d__module" ],
    [ "PE_Types module documentation", "group___p_e___types__module.html", "group___p_e___types__module" ],
    [ "RTC module documentation", "group___r_t_c__module.html", "group___r_t_c__module" ],
    [ "TimerInt0 module documentation", "group___timer_int0__module.html", null ],
    [ "TimerIntLdd1 module documentation", "group___timer_int_ldd1__module.html", "group___timer_int_ldd1__module" ],
    [ "TU1 module documentation", "group___t_u1__module.html", "group___t_u1__module" ],
    [ "UART0 module documentation", "group___u_a_r_t0__module.html", "group___u_a_r_t0__module" ],
    [ "UART2 module documentation", "group___u_a_r_t2__module.html", "group___u_a_r_t2__module" ],
    [ "Vectors module documentation", "group___vectors__module.html", null ],
    [ "Interrupt vector numbers", "group___interrupt__vector__numbers.html", "group___interrupt__vector__numbers" ],
    [ "Peripheral type defines", "group___peripheral__defines.html", "group___peripheral__defines" ],
    [ "Backward Compatibility", "group___backward___compatibility___symbols.html", null ],
    [ "ADC0Events module documentation", "group___a_d_c0_events__module.html", "group___a_d_c0_events__module" ],
    [ "Events module documentation", "group___events__module.html", "group___events__module" ],
    [ "main module documentation", "group__main__module.html", "group__main__module" ],
    [ "TimerInt0Events module documentation", "group___timer_int0_events__module.html", "group___timer_int0_events__module" ],
    [ "UART0Events module documentation", "group___u_a_r_t0_events__module.html", "group___u_a_r_t0_events__module" ],
    [ "UART2Events module documentation", "group___u_a_r_t2_events__module.html", "group___u_a_r_t2_events__module" ]
];